version: '3.8'

services:
  fastapi-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount only app directory for development to avoid copying all files
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - WORKERS=2
      - PORT=8000
      - DEBUG=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
